### PR TITLE
x509.UnsupportedExtension is gone in cryptography >= 2.1

### PR DESCRIPTION
**Pull request by jlaine**
This fixes the issue reported in #1341

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Thanks @jlaine. I'm not sure we can just remove this without increasing the minimum version we require in `setup.{py,cfg}`. That said, I wonder if we could alias the exception on 2.2 or newer such that we can handle older versions and newer versions

**Comment by njsmith** [comment]
Requiring the latest version of pyopenssl/cryptography seems pretty reasonable. (In fact the latest version of pyopenssl does require the latest version of cryptography.)

If you want to alias it instead, I guess something like this would work:

```python
try:
    from cryptography.x509 import UnsupportedExtension
except ImportError:
    # Putting this in an except: will never catch anything, because no-one ever throws it
    class UnsupportedExtension(Exception):
        pass
```

**Comment by haikuginger** [comment]
The try/except is one option; does `cryptography` have a base exception class that we could import instead of each of these three?

**Comment by jlaine** [comment]
The current release of pyopenssl only supports cryptography >= 2.1.4, and the next one will support only >= 2.2.1, do we really want to support older versions? This would means explicitly testing against these older versions.

**Comment by sigmavirus24** [comment]
> do we really want to support older versions?

I'm pretty sure we already do our best to test older versions. The short of it is that downstream packagers cherry-pick (in my experience) what things they actually update. Things like cryptography and pyopenssl make it hard for us to raise our minimum versions if their already packaged software works fine with an older version and would break by us updating our minimum requirement.

We can try to push the entire world forward, but that will be very unpleasant for the maintainers of this project.

**Comment by jlaine** [comment]
I was looking throught the travis config files and I don't see any entries for testing different pyopenssl / crypto versions, can someone point me to the right place maybe?

**Comment by njsmith** [comment]
It would also be really nice if this PR had a test that exercised that `except:` block, so we don't hit this again.

I asked about this on #cryptography, and @reaperhulk generously made this cert with a duplicate extension, so it should trigger that "A problem was encountered with the certificate..." block:

https://gist.github.com/reaperhulk/70f2c4daba422a7f83965111cc2134e3

**Comment by jlaine** [comment]
The osx tests seem pretty flaky, the failures don't seem to be related to these changes.

**Comment by sigmavirus24** [comment]
@jlaine the OSX tests are passing but codecov shows this as a decrease in overall project coverage. Please address that.

**Comment by jlaine** [comment]
The codecov seems to be out of date, and based on the failing test run, the changes it is reporting are in unrelated files.

The exception I changed was in a branch which was previously untested, and I added a test for it.

The only part of the change which is likely to negatively affect coverage is the try/except I was asked to add around the import: as pointed out earlier, the building matrix always used the latest version of cryptography, which does not exercise the "except".

**Comment by jlaine** [comment]
Ok I give up, the test suite on osx seems really random.

**Comment by sigmavirus24** [comment]
@jlaine your empty commit seems to have passed all the CI. What is random at the moment?

**Comment by jlaine** [comment]
Hm, I guess I was wrong but I could have sworn both Python 3.6 and 3.7 had failed on osx.

**Comment by haikuginger** [comment]
It did. I re-ran it.

**Comment by SethMichaelLarson** [comment]
Thanks @jlaine!

**Pull request merged**
