### PR TITLE
Updating links to SSL warning help page. Fixes #918

### LINKED ISSUE #918: Doc link for SSL warnings is broken
#887 removed docs/security.rst, but it's still referenced as https://urllib3.readthedocs.org/en/latest/security.html in the message for InsecureRequestWarning, InsecurePlatformWarning, and SNIMissingWarning.

For example:

```
requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

```
requests\packages\urllib3\connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35803462-doc-link-for-ssl-warnings-is-broken?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jonparrott**

### CODE REVIEW

**Comment by Lukasa** [comment]
So this only deals with part of this issue @jonparrott, what's the plan for ensuring the old links continue to work?

**Comment by sigmavirus24** [comment]
@Lukasa I believe @jonparrott described this on #918 and it needs ReadTheDocs configuration on the website.

**Comment by jonparrott** [comment]
Yep, I added some instructions on setting up a redirect for the old URL. :)

**Comment by sigmavirus24** [comment]
I'm tempted to just merge this.

**Comment by haikuginger** [comment]
👍

**Comment by Lukasa** [comment]
@jonparrott Would you like to update your branch to the current master for merging, please?

**Comment by jonparrott** [comment]
@Lukasa updated. I swear it was up to date when I submitted it. D:

**Pull request merged**
