### PR TITLE
Adding socks extra to setup.cfg

### LINKED ISSUE #863: urllib3 1.15.1 does not provide the extra 'socks'
When installing urllib3 using `pip` according to the instructions on the [Contrib Modules](https://urllib3.readthedocs.io/en/latest/contrib.html#socks) page, the following messages are produced:

    $ pip install -U urllib3[socks]
    Collecting urllib3[socks]
      Using cached urllib3-1.15.1-py2.py3-none-any.whl
      urllib3 1.15.1 does not provide the extra 'socks'
    Installing collected packages: urllib3
    Successfully installed urllib3

And the `PySocks` package is not installed, resulting in the following error on import:

    $ python -c 'from urllib3.contrib.socks import SOCKSProxyManager'
    /home/user/.local/lib/python2.7/site-packages/urllib3/contrib/socks.py:31: DependencyWarning: SOCKS support in urllib3 requires the installation of optional dependencies: specifically, PySocks.  For more information, see https://urllib3.readthedocs.org/en/latest/contrib.html#socks-proxies
      DependencyWarning
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/user/.local/lib/python2.7/site-packages/urllib3/contrib/socks.py", line 21, in <module>
        import socks
    ImportError: No module named socks

This occurs with both Python 2.7 and 3.5.  It appears to be similar to #684 which was resolved by adding `metadata` to `setup.cfg` in #706.  Perhaps a similar fix for `socks` is needed?

Thanks,
Kevin

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/34320961-urllib3-1-15-1-does-not-provide-the-extra-socks?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by haikuginger**
Should resolve #863, unless I'm very much mistaken.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
This is definitely correct. Thanks @haikuginger

**Comment by shazow** [comment]
Thank you!

**Comment by haikuginger** [comment]
🍰

**Comment by shazow** [comment]
:custard:!

**Pull request merged**
