### PR TITLE
Rely on six to import httplib or http.client

### PR DESCRIPTION
**Pull request by sigmavirus24**
Regarding https://github.com/elastic/elasticsearch-py/issues/253

### CODE REVIEW

**Comment by Lukasa** [comment]
Does this actually solve the problem in the linked issue? Why is `six` not affected when we are?

**Comment by sigmavirus24** [comment]
`six` handles this better by explicitly checking for Python version: https://github.com/shazow/urllib3/blob/master/urllib3/packages/six.py#L110 so on Python 2, `pies` won't break us. `python-future` shouldn't either but appears to be. Either way, six means we don't need to be conscious of the ordering of our imports for `httplib`.

**Comment by Lukasa** [comment]
Yeah, that's fair enough. Ok, I'm happy to go with this. =)

**Pull request merged**
