### PR TITLE
Update connectionpool.py

### PR DESCRIPTION
**Pull request by springjools**
Update debug print to proper DEBUG log level

### CODE REVIEW

**Comment by haikuginger** [comment]
It looks good to me.

**Comment by springjools** [comment]
Hmm, I just edited it in github editor, forgot that python is so picky with tabs. Should I fix and resubmit the PR ?

**Comment by jeremycline** [comment]
It _is_ quite noisy if you're working with a server that doesn't do keep-alive. 

Personally I like it at the info level and it's helped me quickly recognize when a server isn't configured as it should be, but I'm okay turning on debug logs for this kind of this.

**Comment by Lukasa** [comment]
@springjools There's no need to resubmit: you can just make further commits on this branch. If you find your branch on GitHub you can edit inline and just make a new commit to fix up the indentation. =)

**Comment by Lukasa** [comment]
Closed in favour of #967.

**Pull request closed without merging**
