### PR TITLE
test chunked response with gzip encoding

### PR DESCRIPTION
**Pull request by t-8ch**
duplicates #441

### CODE REVIEW

**Comment by t-8ch** [comment]
I hate those

**Comment by t-8ch** [comment]
One last time...

**Comment by shazow** [comment]
Someday you'll learn to love the socket-level tests. :)

**Comment by sigmavirus24** [comment]
urllib3 or: How I Learned to Stop Worrying and Love the Socket-level Test

**Comment by shazow** [comment]
If I could get a corporate sponsor to fund a bounty for a task, port more tests to socket-level and flesh out that suite would be near the top of my list.

**Pull request merged**
