### PR TITLE
proper use of super().__init__() call

### PR DESCRIPTION
**Pull request by t-8ch**
Amends #640...

### CODE REVIEW

**Comment by Lukasa** [comment]
Yeah, this is a no brainer. Merge it @shazow! :sparkles:

**Comment by sigmavirus24** [comment]
:custard:

**Comment by shazow** [comment]
> :custard: 

:custard:

**Comment by sigmavirus24** [comment]
>> :custard: 

> :custard:

:custard:

**Comment by shazow** [comment]
>> :sparkles: 

> :sparkles: 

:sparkles: 

THREE IN A ROW!

**Comment by sigmavirus24** [comment]
:rainbow: :rainbow: 

OMG IT'S A DOUBLE RAINBOW! IT'S SO BEAUTIFUL!

**Comment by t-8ch** [comment]
Well, that escalated quickly :fireworks:

**Pull request merged**
