### PR TITLE
Import more from six

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by sigmavirus24** [comment]
@scop have you found everything that can be imported from six?

@Lukasa @haikuginger if the answer to ^ is no, can we hold off until this is completed?

**Comment by haikuginger** [comment]
I want this badly, but, like @sigmavirus24, I also want it done once and for all. @scop, if you haven't already, do you want to try searching the repo for any other instances of `except ImportError` that can be replaced with `six` helpers?

**Comment by scop** [comment]
This commit was done by looking at the output of `git grep -B 4 ImportError`, I think I caught all of what was there. I just did another run with `git grep -B 4 except:` and there's one more in it, will force-push in a jiffy.

**Comment by haikuginger** [comment]
Okay; in that case I'm 👍. @sigmavirus24, @Lukasa, any other thoughts?

@scop, if you could go ahead and rebase on master, that'd be great.

**Comment by Lukasa** [comment]
I'm happy. We can merge when we get the rebase. =D

**Comment by scop** [comment]
Rebased.

**Comment by Lukasa** [comment]
Nice, thanks @scop! :custard:

**Pull request merged**
