### PR TITLE
only normalize http(s) urls

### PR DESCRIPTION
**Pull request by nateprewitt**
This is a proposed solution for #1080. We'll now restrict our host lower-casing to only schemes we've noted to be "normalizable".

### CODE REVIEW

**Comment by sigmavirus24** [comment]
@lslebodn had an interest in tackling this. I think we should have let them submit their change. There isn't any urgency in this.

**Comment by nateprewitt** [comment]
@sigmavirus24, I believe @lslebodn's primary concern had been seeing this fixed for Debian as he [mentioned](https://github.com/kennethreitz/requests/pull/3738#issuecomment-268805728) in the Requests issue.

That said, there definitely isn't a rush on this. If you would like to pick this up @lslebodn, I'll gladly close this out. I'd (possibly mistakenly) inferred your question yesterday to be asking if the work was done yet. The turn around on a release of this will take a while to reach Requests.

**Comment by lslebodn** [comment]
I am very glad you provided a fix I would find a time next week :-)
Thank you very much @nateprewitt.

**Comment by nateprewitt** [comment]
All yours @lslebodn :)

**Comment by nateprewitt** [comment]
I'm still a little unclear on whether there is other intent to fix #1080, so I'm reopening this PR since we're now a month on.

This should be ready to go (after a test restart), unless you've already started work on this @lslebodn.

**Comment by lslebodn** [comment]
I am confused. I thought it's already fixed. Why do we need to reooen it?

**Comment by nateprewitt** [comment]
Sorry @lsleboldn, @Sigmavirus24 was under the impression you'd wanted to submit the PR, so we closed this one waiting for you to open one.

I think this was just some miscommunication of intentions. The work is done and ready to go here, we just need @Lukasa to push the button. Then hopefully it will make it into 2.14.0.

**Comment by Lukasa** [comment]
Want to rebase this onto the current master branch?

**Comment by nateprewitt** [comment]
Should be set after tests finish :)

**Pull request merged**
