### PR TITLE
Handle EPIPE on shutdown from pyopenssl

### LINKED ISSUE #612: Uncaught exception from pyOpenSSL's shutdown call
See https://github.com/pypa/pip/issues/2753 for more details

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/13757454-uncaught-exception-from-pyopenssl-s-shutdown-call?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Lukasa**
This should resolve #612 and pypa/pip#2753.

### CODE REVIEW

**Comment by t-8ch** [comment]
Maybe we should not confuse `close()` and `shutdown()`. The stdlib also has a dedicated shutdown. What about. `close = _drop`?

**Comment by Lukasa** [comment]
@t-8ch Not sure I fully understand your point. Right now `_drop` is implemented in terms of `close`, which is implemented in terms of `shutdown`.

**Comment by t-8ch** [comment]
Hm, should have woken up properly first...
I mean, the stdlib does not use `shutdown` on `close`, so our compat wrapper should also not do so.
This means, we don't shut down properly which should be addresses in a separate issue, also covering our non-pyopenssl codepath

**Comment by Lukasa** [comment]
@t-8ch I don't see any `close` logic in pyopenssl, so I take it your plan is that we just directly close the socket and let the `OpenSSL.SSL.Connection` object go out of scope?

**Comment by t-8ch** [comment]
https://pythonhosted.org/pyOpenSSL/api/ssl.html#OpenSSL.SSL.Connection.close

**Comment by Lukasa** [comment]
Ah, I see, sorry: the `OpenSSL.SSL.Connection` object is a proxy to the socket, so it still has socket methods on it.

So, the reason not to do that is the reason we're using `shutdown` in the first place, which is that we do not cleanly shut the connection down: it's possible that OpenSSL has data it wants to write to the socket that it has not been able to write.

I take it that we therefore have similar 'bugs' with the stdlib, that's your assessment?

**Comment by t-8ch** [comment]
@Lukasa exactly

**Comment by Lukasa** [comment]
So let's ask the follow-up question: do we care? The stdlib currently manages closing the socket in the `HTTPConnection` class, and doesn't bother calling `shutdown`. Should we just be calling `close` and being done with it?

**Comment by t-8ch** [comment]
Weirdly enough it does do a shutdown in the `HTTPSConnection` if a handshake fails.
I would say: go for plain close and try to cook up a testcase for the bug.

We should also provider a `shutdown()` method for consistency (and maybe later use)

**Comment by Lukasa** [comment]
Alright, that feels like a good patch. I feel a bit bad if I rewrite this code to do that (because it's totally your idea), so it might be better if you push up that patch and I'll review it. =)

**Comment by Lukasa** [comment]
Closing in favour of #614.

**Comment by shazow** [comment]
Thank you both. :)

**Comment by smtakeda** [comment]
Hi, I came across this issue while I was investigating EPIPE handling. I just found OpenSSL/SSL.py no longer has `Connection.close` method in the code on Github.
https://github.com/pyca/pyopenssl/blob/master/src/OpenSSL/SSL.py

I'm not sure what change has happened from this repository: https://pythonhosted.org/pyOpenSSL/api/ssl.html#OpenSSL.SSL.Connection.close

but the doc still says `Connection.close` exists:
https://pyopenssl.readthedocs.org/en/latest/api/ssl.html#OpenSSL.SSL.Connection.close

Maybe I should raise this PyOpenSSL issue tracker or am I missing something? If so, calling `Connection.close` won't work then?

**Comment by Lukasa** [comment]
@smtakeda It's fine. =) The `Connection.close` method still exists, but it exists as a proxy through to the underlying `socket` object. The logic for it is [here](https://github.com/pyca/pyopenssl/blob/master/src/OpenSSL/SSL.py#L1123-L1133).

The code will function correctly. Thanks for your concern!

**Comment by smtakeda** [comment]
oh, sorry about my ignorance and thanks for the quick reply. I'm glad that I leaned something new in Python and I can apply the same patch to my copy of urllib3. Thank you.

**Comment by Lukasa** [comment]
> oh, sorry about my ignorance

There is never any need to apologise for not knowing something. We all start out not knowing, and then we learn. You were polite and considerate, which is all you need to be. Don't worry about not knowing things: you're learning!

(If you want to ask more questions, you can join us in IRC at #python-requests.)

**Pull request closed without merging**
