### PR TITLE
Don't try to run IPv6 tests if IPv6 is disabled at runtime

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
Hmmm, travis appears to be failing, but in precisely the way I expected this patch to resolve...

**Comment by Lukasa** [comment]
Those tests use IPv6HTTPDummyProxyTestCase, which I think your patch missed.

**Comment by alex** [comment]
@Lukasa good catch, fixed. (flake8 is still failing, should I fix those up, or can that go in it's own PR?)

**Comment by Lukasa** [comment]
They can be fixed separately, thanks Alex!

**Comment by Lukasa** [comment]
Oh, lol, no they can’t: they’re a required status

**Pull request merged**
