### PR TITLE
Respect `release_conn=False` after retry

### LINKED ISSUE #651: Likely bug in retry/release-conn code, need tests
In this change: https://github.com/shazow/urllib3/pull/647/files#diff-211abff6a07837e4a89a8663a89d2c84R582

@jlatherfold writes:

> For the (TimeoutError, HTTPException, SocketError, ConnectionError) exception handler you don't raise (presumably because there may be retries) and you will go on to release the conn and make another call to urlopen (if retries). But you call it with release_conn=True (since you've just set it to true) - what happens if that call succeeds? You'll release the conn back to the pool before the response is read. At least that's what it looks like to me.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/21823734-likely-bug-in-retry-release-conn-code-need-tests?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jmoldow**
Respect `ConnectionPool.urlopen(release_conn=False)`, making sure not to release the connection, even after a retry.

If a request failed but then succeeded after a retry, the connection would be released, contrary to what the user requested.

Fixes #651.

### CODE REVIEW

**Comment by Lukasa** [comment]
Thanks for this! This fix seems like a really good one.

However, the size of the diff for the tests is *massive*, and I think that's because you're using the test server to repro this. That's fine, but for a problem like this you may find it takes less code (and is more comprehensible) to write a socket level test. Have you considered doing that?

**Comment by shazow** [comment]
> for a problem like this you may find it takes less code (and is more comprehensible) to write a socket level test. 

+1, I'd like to move as many tests as possible into socket-level tests as they're far less flaky and easier to debug.

**Comment by jmoldow** [comment]
I tried writing a socket-level test, but I couldn't figure it out. Would one of you be able to write the socket-level test for this? @Lukasa @shazow

**Comment by Lukasa** [comment]
I can do if that's something you want me to do. It'd basically just be a variation on `test_connection_closed_on_read_timeout_preload_false`. If you take a look at that test and still don't think you're comfortable writing that test let me know, and I'll write it myself.

**Comment by jmoldow** [comment]
@Lukasa That was the test I was trying to copy. However, there some important differences:

- That test has the timeout on the `read`, but both `urlopen` calls succeed. My test doesn't involve `read` at all, and the timeout(s) are during `urlopen`.
- That test has one unsuccessful call followed by one successful call. I was hoping to have two unsuccessful calls, followed by one successful call. The reason being, I wanted to have one failed `urlopen(retries=0)`, and one successful (but with one retry) `urlopen(retries=1)`. The reason for the former, is to guarantee that the latter is in fact going through the retry logic.
- That test used a `threading.Event` to force the timeout. But we can't do that for the `urlopen(retries=1)`, since there's no straightforward way to set the event between retries.
  - In the testserver test I wrote, I introduced the concept of a server-side delay. So maybe you could do that here too, instead of using an `Event`.
  - I suppose you could write a `Retry` subclass, which sets the event in `Retry.increment`. I suppose you could also use that mechanism to assert that there was in fact a retry.

I tried to resolve those differences, but wasn't able to figure out how to do it (I think I don't fully understand the rules for how the `Response` object is generated from the socket).

**Comment by jmoldow** [comment]
Also, if the size of the test diff is too much, we could remove some superfluous stuff. For example, don't technically need to make any assertions of `pool.num_connections`, since it isn't directly related to the functionality at hand. Similarly, can remove the final part of the tests that call `Response.release_conn()`, since that is testing different behavior. If you want me to remove those, it'd make the tests I wrote simpler to review.

**Comment by Lukasa** [comment]
@jmoldow Ok, I've written what I believe is a correct socketlevel test in lukasa/urllib3@3d4d37e0b2b119766576363fa3f418c7aa959290, in the `issue/866` branch on my fork. Want to give that a try?

**Comment by jmoldow** [comment]
Thanks @Lukasa . I confirmed that your test passes on this branch, and reproduces the issue on master. I've incorporated the test into this pull request, with some changes (such as the name of the test - the old name didn't accurately describe what was being tested).

I've also simplified the other tests I had written. They are now much smaller and more comprehensible.

**Comment by Lukasa** [comment]
Ok, cool, this change looks good. I'm :+1:, but of course I'd like @shazow to review too. Bonus points for reviews from @sigmavirus24 and @haikuginger.

**Comment by haikuginger** [comment]
It looks good to me. Logical change! 👍

**Comment by shazow** [comment]
Do we still need the dummyserver changes/tests?

**Comment by jmoldow** [comment]
I can remove the `test/with_dummyserver/test_connectionpool.py` / `dummyserver/testcase.py` changes if you'd like.

**Comment by shazow** [comment]
If you're comfortable that the same functionality is exercised through socketlevel tests, I think that'd be best. My long-term goal is to get rid of the dummyserver so fewer things to prune later would be nice. :)

**Comment by jmoldow** [comment]
@shazow done

**Comment by shazow** [comment]
Excellent, thank you very much @jmoldow. :)

**Comment by jmoldow** [comment]
You're welcome. Thank you for merging @shazow

**Comment by shazow** [comment]
✨ :custard: ✨

**Pull request merged**
