### PR TITLE
Use relative imports in SOCKS module.

### LINKED ISSUE #772: Broken vendoring in socks contrib module
Awkwardly, the SOCKS contrib module doesn't work properly when vendored because it tries to do an absolute import. We should probably rewrite it to use relative imports.

My bad.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29479936-broken-vendoring-in-socks-contrib-module?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Lukasa**
Resolves #772.

It may be worth pushing out a 0.14.1 with this change in it at some point soon, but that's totally up to you @shazow.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
0.14.1 -> 1.14.1 ;)

**Comment by sigmavirus24** [comment]
I am so tempted to just merge this. :tongue:

**Comment by shazow** [comment]
This doesn't affect urllib3 at all, right? Just for requests? Is it necessary to publish a release if it won't affect unvendored distributions?

**Comment by Lukasa** [comment]
No immediate rush. =)

**Pull request merged**
