### PR TITLE
v2.0 release candidate, finally fixed urllib3's biggest bug

### PR DESCRIPTION
**Pull request by shazow**
This is a very important release as urllib3 had a huge bug present since day 1, and it took us this long to fix it: The name. It's a terrible name, by far my biggest regret as far as design decisions go.

Starting with version 2.0, we will shed our shame and rename urllib3 to urllib4.

### CODE REVIEW

**Comment by Lukasa** [comment]
Long overdue. Couldn't agree more. :+1: * :100: :shipit:

**Comment by t-8ch** [comment]
What about urlllib3

**Comment by shazow** [comment]
@t-8ch requestslib3 was a close contender.

**Comment by gwintrob** [comment]
:+1:

**Comment by t-8ch** [comment]
urllibπ

**Comment by sigmavirus24** [comment]
:-1: tests are failing.

**Comment by shazow** [comment]
@sigmavirus24 As part of this transition, we're also changing our tests policy.

**Comment by shazow** [comment]
While we're making sweeping changes, how do we feel about vendoring requests?

**Comment by Lukasa** [comment]
@shazow I feel like the right thing to do is actually to vendor in the python stdlib.

**Comment by sigmavirus24** [comment]
> While we're making sweeping changes, how do we feel about vendoring requests?

+1000 :100:

**Comment by shazow** [comment]
@Lukasa I like the idea of vendoring requests because then each version would have the previous version vendored, and we could build a Makefile to bootstrap the vendorception from pre-2.0.

**Comment by kevinburke** [comment]
Not shipping urllib4 until it can do email.



On Wednesday, April 1, 2015, Ian Cordasco <notifications@github.com> wrote:

> While we're making sweeping changes, how do we feel about vendoring
> requests?
>
> +1000 [image: :100:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shazow/urllib3/pull/580#issuecomment-88626701>.
>


-- 

--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by kevinburke** [comment]
Should probably also build in a Linux init system

On Wednesday, April 1, 2015, Kevin Burke <kev@inburke.com> wrote:

> Not shipping urllib4 until it can do email.
>
>
>
> On Wednesday, April 1, 2015, Ian Cordasco <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> While we're making sweeping changes, how do we feel about vendoring
>> requests?
>>
>> +1000 [image: :100:]
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/shazow/urllib3/pull/580#issuecomment-88626701>.
>>
>
>
> --
>
> --
> Kevin Burke
> phone: 925.271.7005 | twentymilliseconds.com
>
>

-- 

--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by shazow** [comment]
Slept on it, maybe not a great idea. :P

**Pull request closed without merging**
