### PR TITLE
Remove all uses of nose from the codebase

### PR DESCRIPTION
**Pull request by alexwlchan**
Related: #1160.

### CODE REVIEW

**Comment by Lukasa** [comment]
Ok, Appveyor 3.3 is failing for shitty Appveyor reasons. Is there any reason for us to keep supporting 3.3?

**Comment by Lukasa** [comment]
I mean, Requests supports it, but...probably it shouldn't.

**Comment by Lukasa** [comment]
Sadly I may have to fix this. 🙁

**Comment by alexwlchan** [comment]
> Is there any reason for us to keep supporting 3.3?

🔥 🔥 🔥

**Comment by Lukasa** [comment]
Aha, [this](https://cryptography.io/en/latest/changelog/#v2-0) is the problem we're encountering. To maintain support for Python 3.3 is possible so long as we cap the cryptography version, which I don't think we should do, so I think we should begin sunsetting Python 3.3 support.

**Comment by alexwlchan** [comment]
Woohoo, a green build!

**Pull request merged**
