### PR TITLE
Fix all flake/linter errors within tests

### PR DESCRIPTION
**Pull request by SethMichaelLarson**
Work so far on fixing all flake / lint errors in the `test/` directory. Also adds that directory to the list of locations that are checked by `flake8` by the CI.

This PR does not yet check for line too long because of how many instances there are of that error, I will work on that tonight.

### CODE REVIEW

**Comment by SethMichaelLarson** [comment]
The tests should fail, I'm going to make the line-to-long commit last because it's most likely to garner some comments. 

Also the dictionary duplicated keys is a flake error too apparently so I think it'd be okay to fix it in this PR?

**Comment by SethMichaelLarson** [comment]
Would like a review on the last commit about E501. I didn't change any code functionality but some people have strong opinions how lines should wrap. :)

**Comment by SethMichaelLarson** [comment]
That should be the last commit for this PR. :)

**Comment by Lukasa** [comment]
Awesome, LGTM. Let's merge this.

**Pull request merged**
