### PR TITLE
may be cause SSLError when has installed pyopenssl

### PR DESCRIPTION
**Pull request by dongweiming**
when i install django i found this error:

```python
pip install django     
Downloading/unpacking django
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/pip-1.6.dev1-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/pip-1.6.dev1-py2.7.egg/pip/commands/install.py", line 274, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/pip-1.6.dev1-py2.7.egg/pip/req/req_set.py", line 286, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/pip-1.6.dev1-py2.7.egg/pip/index.py", line 194, in find_requirement
    page = self._get_page(main_index_url, req)
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/pip-1.6.dev1-py2.7.egg/pip/index.py", line 568, in _get_page
    session=self.session,
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/pip-1.6.dev1-py2.7.egg/pip/index.py", line 670, in get_page
    resp = session.get(url, headers={"Accept": "text/html"})
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/pip-1.6.dev1-py2.7.egg/pip/_vendor/requests/sessions.py", line 395, in get
    return self.request('GET', url, **kwargs)
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/pip-1.6.dev1-py2.7.egg/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/pip-1.6.dev1-py2.7.egg/pip/_vendor/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/pip-1.6.dev1-py2.7.egg/pip/_vendor/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/pip-1.6.dev1-py2.7.egg/pip/_vendor/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/pip-1.6.dev1-py2.7.egg/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 480, in urlopen
    body=body, headers=headers)
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/pip-1.6.dev1-py2.7.egg/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 285, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/pip-1.6.dev1-py2.7.egg/pip/_vendor/requests/packages/urllib3/connection.py", line 164, in connect
    ssl_version=resolved_ssl_version)
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/pip-1.6.dev1-py2.7.egg/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 382, in ssl_wrap_socket
    cnx.do_handshake()
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1442, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1187, in _raise_ssl_error
    _raise_current_error()
  File "/Users/dongweiming/firefly/venv/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert handshake failure')]

Storing debug log for failure in /Users/dongweiming/.pip/pip.log
```
This is very confusing Because it always work nice.

Because i install pyopenssl . if i uninstall it. it will be ok.

```
$pip uninstall pyopenssl -q
Proceed (y/n)? y
$pip install django   
Downloading/unpacking django
  Downloading Django-1.8.2-py2.py3-none-any.whl (6.2MB): 6.2MB downloaded
Installing collected packages: django
Successfully installed django
Cleaning up...
```

### CODE REVIEW

**Comment by Lukasa** [comment]
My psychic powers tell me that you are using OS X, and that you have a version of Python you've installed from Homebrew. Am I right?

**Comment by dongweiming** [comment]
@Lukasa yes. But the Python is OS X's original

**Comment by Lukasa** [comment]
Can you run the following two commands for me please?

`python -c 'import ssl; print ssl.OPENSSL_VERSION'`
`python -c 'from OpenSSL import SSL; print SSL.SSLeay_version(SSL.SSLEAY_VERSION)'`

**Comment by dongweiming** [comment]
```python
$python -c 'import ssl; print ssl.OPENSSL_VERSION'
OpenSSL 0.9.8zc 15 Oct 2014
$python -c 'from OpenSSL import SSL; print SSL.SSLeay_version(SSL.SSLEAY_VERSION)'
OpenSSL 0.9.8zc 15 Oct 2014
```

**Comment by Lukasa** [comment]
Interesting! It doesn't seem like there's any reason for PyOpenSSL to get this wrong. *However*, you're also using a very old version of pip, which means a very old version of pyopenssl. Can you try upgrading pip and give it another shot with PyOpenSSL installed?

**Comment by dongweiming** [comment]
But i use the newest pip:

```python
which pip
/Users/dongweiming/firefly/venv/bin/pip
$pip --version
pip 1.6.dev1 from /Users/dongweiming/firefly/venv/lib/python2.7/site-packages/pip-1.6.dev1-py2.7.egg (python 2.7)
```

**Comment by Lukasa** [comment]
@dongweiming That is not the newest version of pip, this is:

```bash
% pip --version
pip 7.0.3 from /usr/local/lib/python2.7/site-packages (python 2.7)
```

**Comment by dongweiming** [comment]
@Lukasa  Oh. i use my own repository setup pip. but has a long time not sync to upstream. updated it works

**Comment by dongweiming** [comment]
@Lukasa thanks.

**Pull request closed without merging**
