### PR TITLE
pyopenssl: close != shutdown

### LINKED ISSUE #612: Uncaught exception from pyOpenSSL's shutdown call
See https://github.com/pypa/pip/issues/2753 for more details

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/13757454-uncaught-exception-from-pyopenssl-s-shutdown-call?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by t-8ch**
fixes #612, see #613

### CODE REVIEW

**Comment by Lukasa** [comment]
\o/ LGTM. :cake: :sparkle:

**Comment by thanatos** [comment]
When could I expect a release for this? I think I'm seeing https://github.com/pypa/pip/issues/2753, which is waiting on this bug to be released to actually be fixed.

**Comment by shazow** [comment]
@thanatos This was included in the v1.11 release a few months ago.

**Comment by thanatos** [comment]
Ah, thanks! I had looked at commit on the fork, not the commit here, and misread.

**Pull request merged**
