### PR TITLE
Pointing flake8 specifically at the urllib3 package

### LINKED ISSUE #914: Flake8 runs on entire virtualenv inside the repository
When running `make test-all`, flake8 will run on the entirety of the repository, including the `site-packages` directory of any virtual environment stored therein.

The solution is to ~~create an upstream pull request bringing the entire standard library into line with flake8 standards~~ point flake8 specifically at the urllib3 package.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35730310-flake8-runs-on-entire-virtualenv-inside-the-repository?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by haikuginger**
Fixes #914.

### CODE REVIEW

**Comment by Lukasa** [comment]
Woo! :custard:

**Comment by sigmavirus24** [comment]
This excludes the tests, no? Why not update Flake8's config instead?

**Comment by haikuginger** [comment]
It looks like we're already excluding tests in `setup.cfg`, along with a couple other things. But, we can certainly get the effect we want using the config there and excluding the pattern `site-packages`; that way, it isn't sensitive to the specific name of the virtualenv. Does that sound good to everyone?

**Comment by sigmavirus24** [comment]
That sounds fine.

**Comment by Lukasa** [comment]
Suits me!

**Pull request merged**
