### PR TITLE
Fix compatibility with tornado 4.3+

### PR DESCRIPTION
**Pull request by felixonmars**
`HTTPHeaders` is not JSON serializable, so make it a dict first.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Preliminary 👍

**Comment by felixonmars** [comment]
codecov seems stuck :/

**Comment by felixonmars** [comment]
OK, a branch update fixed codecov :)

**Comment by sigmavirus24** [comment]
Thanks @felixonmars !

**Pull request merged**
