### PR TITLE
Try using codecov.

### PR DESCRIPTION
**Pull request by Lukasa**
Ok, let's see if we can get this working.

### CODE REVIEW

**Comment by SethMichaelLarson** [comment]
Once it works we can turn on the required check for codecov in GitHub and turn off the 100% coverage checks in the individual build jobs, right?

**Comment by Lukasa** [comment]
@SethMichaelLarson That would be my general plan, yes.

**Comment by SethMichaelLarson** [comment]
@lukasa Codecov will give a big output message usually if it didn't work, the results sometimes take some time to show up on their end though.

**Comment by Lukasa** [comment]
Yeah, but in this case I can see that codecov failed to upload. =D

**Comment by SethMichaelLarson** [comment]
Ah okay, just figured I'd tell you in case you haven't used codecov before.

**Comment by SethMichaelLarson** [comment]
May have been a mistake setting up Mac OS then Codecov in that order. :stuck_out_tongue_winking_eye:

**Comment by Lukasa** [comment]
Yes, I have become aware of that. 😭

**Comment by SethMichaelLarson** [comment]
@Lukasa might be a good idea to reduce the Mac OS builds by only requiring Mac OS + [py26, py33, py34] for building against master. Mac OS + [py27, py35] have faster setup times it seems, especially py27.

**Comment by Lukasa** [comment]
Eh, it's ok. I'm finding things to do in between waiting for these builds. I highly recommend doing the same. ;)

**Comment by SethMichaelLarson** [comment]
Oh I am, just whenever I check back seeing multiple builds stacked up in the queue haha :P

**Comment by SethMichaelLarson** [comment]
Btw just wondering, in our `.travis.yml` we don't cache pip, is there a reason for that?

**Comment by Lukasa** [comment]
There is not, no. =)

**Comment by SethMichaelLarson** [comment]
Is that something that we might be interested in? I don't know how much build times would be affected.

**Comment by Lukasa** [comment]
Yeah, it's probably worth doing. I'll add it to my task list. ;)

**Comment by SethMichaelLarson** [comment]
Btw you should cancel old builds that are stacked up, they aren't going to give any new information it'll just delay the build you actually want to see by an hour.

**Comment by Lukasa** [comment]
Oh hey that's a solid idea. Thanks for the suggestion!

**Comment by Lukasa** [comment]
Alrighty, that's beginning to work now!

**Comment by SethMichaelLarson** [comment]
Awesome! Once this does a full pass and is merged I'll sync upstream and get a build of my PR. I'll also add the unittest2 stuff we discussed.

**Comment by SethMichaelLarson** [comment]
@Lukasa It looks like the last few builds are still polling for Mac OS machines for builds on py33, p34, and py35. Might want to cancel those, I saw you had previously canceled them so I wonder if Travis is having issues with Mac OS builds.

**Comment by Lukasa** [comment]
@SethMichaelLarson At this point I'm inclined to want to leave them for now. I'd like to let them move through before I head on to the next step relating to `codecov.yml`.

FWIW, the reason I am showing caution here is because I don't have admin on this repo: because it's not in an org, GH doesn't let you grant full permission to another person without transferring the repo to them. This repo should stay as Andrey's, but it means that we might end up encountering some trouble getting the complete codecov integration.

I'm not certain about it, but I'd like to wait and find out.

**Comment by Lukasa** [comment]
Heh, I realise I didn't actually *make* my point there. My point is: I want to give codecov as much time as possible to settle and see a complete run before I do too much. Small steps is good here.

**Comment by SethMichaelLarson** [comment]
Sure thing, I hope my suggestions aren't coming across as pushy or pestering, please tell me if they are. I'm trying to be helpful and I'm excited about these new additions to this repo :)

**Comment by Lukasa** [comment]
Heh, they absolutely aren't! You're doing a fine job with being helpful, you're just always going to bump into a problem with async textual communication whereby it's hard for you to know what advice is new to someone and what advice is something they already know. So it's not a problem for you to err on the side of giving advice that I might already know. =D

**Comment by SethMichaelLarson** [comment]
Okay, thank you for your kindness. :)

**Comment by Lukasa** [comment]
And thank *you* for your hard work and enthusiasm!

**Comment by SethMichaelLarson** [comment]
So it looks like the py35 build failed a test because of a long timeout instead of a short timeout. Hm.

**Comment by Lukasa** [comment]
Uh, right now I see the builds running waiting for a Py35 macOS builder.

**Comment by SethMichaelLarson** [comment]
@Lukasa Strange, either I'm going crazy or Travis is having trouble with it's Mac OS builds because I swore the last build for this PR had completed.

**Comment by Lukasa** [comment]
It wouldn't be the first time that Travis had trouble with its macOS builds.

**Comment by SethMichaelLarson** [comment]
They're apparently low-staffed right now because of a yearly event, so yeah.

**Comment by haikuginger** [comment]
I kicked the build for that one test to make sure it wasn't an ephemeral failure.

**Comment by Lukasa** [comment]
@haikuginger The mystery resolves itself!

**Comment by SethMichaelLarson** [comment]
@haikuginger That explains it, thanks!

**Comment by SethMichaelLarson** [comment]
In case you didn't see it @Lukasa Travis posted on it's Twitter that it had problems with Mac OS but resolved them a few hours ago and it's processing the backlog now. Probably by it's taking so long to get a Mac OS builder.

**Comment by Lukasa** [comment]
Yup, saw it :wink:

**Comment by SethMichaelLarson** [comment]
Success!

**Comment by Lukasa** [comment]
Two more commits inbound.

**Comment by SethMichaelLarson** [comment]
@Lukasa Yeah, these are for codecov.yml and removing the nosetest coverage requirement I'm guessing?

**Comment by Lukasa** [comment]
Exactly so. =D

**Comment by SethMichaelLarson** [comment]
I'm going to hold off on committing anything until this is merged so I can sync ASAP. ;)

**Comment by Lukasa** [comment]
Ok, so I'm going to merge this to trunk now. I have no idea if this will start getting PR stati to show up or not, so if it doesn't I'll have to see if that's a permissions issue.

**Pull request merged**
