### PR TITLE
1075: lazy load idna library

### PR DESCRIPTION
**Pull request by moin18**
Utility to load `idna` library when needed and delete the references once done. Consumed memory will be freed by the GC

Related to issue:  https://github.com/shazow/urllib3/issues/1075

### CODE REVIEW

**Comment by Lukasa** [comment]
Ok, this seems like a gigantic sledgehammer to crack a tiny nut.

Forcing import and unloading of the library repeatedly is a substantial over optimisation that we simply don't require, and operates at the cost of additional CPU resources. We should attempt *only* to delay the import of the module until its first use. Once it is used there is no sense freeing the module: we are better served simply leaving it in memory and allowing the OS to swap the module to disk if it finds that the module is unused.

Simply delaying the import to the point of first use is almost certainly sufficient.

**Comment by moin18** [comment]
@Lukasa Please take a look. Is this sufficient?

**Comment by Lukasa** [comment]
Fab, thanks @moin18! :custard:

**Comment by moin18** [comment]
My first Merge :D Even though it is very trivial. Hope next one will be related to significant impact. I recently decided to contribute to the open source projects :)

**Comment by Lukasa** [comment]
Congratulations @moin18, I'm glad we were able to be your first project! Welcome to the world of OSS. :smile:

**Comment by moin18** [comment]
BTW I accidentally removed my name from the contributors list during the revert of commit. I will be glad if you could add it to the list with your next commit. So that I can show it to my friends :P 

* Moinuddin Quadri <moin18@gmail.com>
  * Lazy load idna library

**Comment by Lukasa** [comment]
Feel free to open a new PR that contains your name in the contributors list and I'll merge it. =)

**Comment by moin18** [comment]
Cool (y) =)

**Pull request merged**
