### PR TITLE
README: Add maintainers list

### PR DESCRIPTION
**Pull request by shazow**
@Lukasa @sigmavirus24 any objections?

### CODE REVIEW

**Comment by Lukasa** [comment]
The irony of the build failing here is strong. ;)

The only objection I have is ordering: I know you ordered alphabetically, but FWIW it feels a bit weird to not have you at the top of that list. Not a strong objection.

**Comment by sigmavirus24** [comment]
tl;dr; what @Lukasa said

> The irony of the build failing here is strong. ;)

Seconded.

> The only objection I have is ordering: I know you ordered alphabetically, but FWIW it feels a bit weird to not have you at the top of that list. Not a strong objection.

Also seconded.

**Comment by shazow** [comment]
lol actually didn't notice it was alphabetic, I'd prefer you both get more recognition than you do. I'm also considering moving the notice further up in the README if you can find a place that makes sense for it.

**Comment by sigmavirus24** [comment]
I don't really see somewhere else that makes sense tbh.

**Comment by shazow** [comment]
We can change the ordering if it keeps bugging you, let me know. :)

**Pull request merged**
