### PR TITLE
Ignore only the unused import error

### PR DESCRIPTION
**Pull request by sigmavirus24**
Instead of waiting for Flake8 3.0.2 tonight, we might as well use Flake8's new feature. =D

### CODE REVIEW

**Comment by haikuginger** [comment]
:+1:

**Comment by Lukasa** [comment]
:+1:

**Comment by haikuginger** [comment]
Beat me to it, @Lukasa!

**Comment by sigmavirus24** [comment]
@Lukasa is speedier than either of us @haikuginger

**Comment by Lukasa** [comment]
SPDYer? Or, maybe even QUICer?

**Comment by haikuginger** [comment]
@sigmavirus24 Well, it makes sense for him to be several hours ahead. :trollface:

**Pull request merged**
