### PR TITLE
Remove useless line in CHANGES.rst

### PR DESCRIPTION
**Pull request by Disassem**

### CODE REVIEW

**Comment by Lukasa** [comment]
Oh, good spot! 😰

**Comment by Lukasa** [comment]
Let's see if I can kick appveyor to rebuild.

**Comment by Lukasa** [comment]
There we go, that got it.

**Comment by SethMichaelLarson** [comment]
Random timeout connecting to localhost. Might want to kick again.

**Comment by SethMichaelLarson** [comment]
Ready for merge :tada:

**Comment by Lukasa** [comment]
🚂🚂🚂

**Pull request merged**
