### PR TITLE
Test with PyPy3 too

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by Lukasa** [comment]
Thanks! However, PyPy3 is Python 3.2, which we don't support.

**Comment by scop** [comment]
PyPy3 v5.2* which this patch adds is Python 3.3, please reconsider.

**Comment by scop** [comment]
Some green proof here: https://travis-ci.org/scop/urllib3/builds/147497199

**Comment by Lukasa** [comment]
I apologise, you're quite right!

**Comment by haikuginger** [comment]
PyPy3 5.2 is still in initial alpha; do we want to hold off on this (at least, publicizing compatibility) until it reaches release?

**Comment by Lukasa** [comment]
Certainly while it's in alpha I'd like to be cautious.

**Comment by Lukasa** [comment]
Let's hold off on this for now until we get to a fuller release.

**Pull request closed without merging**
