### PR TITLE
Do not use `assert`. Use a ValueError instead

### PR DESCRIPTION
**Pull request by t-8ch**
However we have to be backwards compatible.
See #634

### CODE REVIEW

**Comment by shazow** [comment]
Yay looks good. Can you rebase on master?

**Comment by t-8ch** [comment]
@shazow Done

**Comment by shazow** [comment]
@t-8ch You're a wonderful tolerant human being, thank you. :)

**Comment by t-8ch** [comment]
Thanks! You probably more so :-)

**Comment by shazow** [comment]
:custard:

**Comment by sigmavirus24** [comment]
:heart:

**Pull request merged**
