### PR TITLE
Use the public cryptography API for this!

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
@Lukasa Don't feel bad about not doing this before, this API was released about 3 hours ago.

**Comment by Lukasa** [comment]
I know. 😉 I don't feel even slightly bad.

**Comment by alex** [comment]
Test failures on travis don't look like things this is likely to have caused.

**Comment by haikuginger** [comment]
@alex, those look like ephemeral errors to me too, so I've restarted the builds in question.

**Comment by alex** [comment]
Tests are green!

**Comment by sigmavirus24** [comment]
🎉 Thanks @alex!

**Pull request merged**
