### PR TITLE
dev-requirements piprot bump

### PR DESCRIPTION
**Pull request by shazow**
Travis is failing a lot lately, let's try newer versions of things.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
So I was able to reproduce this (by upgrading to 2.2.1). If I remove the following line this problem disappears:

```
PYTHONPATH={env:GAE_PYTHONPATH:}
```

I'm going to find a version of tox that works and file a bug against tox about what appears to be a regression.

**Comment by shazow** [comment]
@sigmavirus24 <3

**Comment by sigmavirus24** [comment]
So this is a regression between 2.1.x and 2.2.x. The problem happens on 2.2.0 and 2.2.1 but not 2.1.1 or prior.

**Comment by sigmavirus24** [comment]
Ah it's already been reported: https://bitbucket.org/hpk42/tox/issues/285/tox-220-breaks-some-toxini-config-files

**Comment by sigmavirus24** [comment]
So 2 things:

1. I'm confused as to how we're intending dev-requirements.txt to be used. It looks like we're using it as test-requirements.txt instead of dev-requirements.txt

2. We're installing tox inside a virtualenv managed by tox in this set-up. Should we separate test and dev requirements so dev-requirements installs tox and whatever else we think developers need and test-requirements is used inside of tox?

**Comment by shazow** [comment]
We don't have a test-requirements.txt; basically dev-requirements.txt has extra deps that we're expecting developers working on urllib3 to use/install in order to have a working environment that can run all the tests, generate coverage, etc.

**Comment by shazow** [comment]
Will push this off for another day (prolly when tox is fixed).

**Pull request closed without merging**
