### PR TITLE
Convert readthedocs link for their .org -> .io migration for hosted projects

### PR DESCRIPTION
**Pull request by adamchainz**
As per their email ‘Changes to project subdomains’:

> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.

Test Plan: Manually visited all the links I’ve modified.

### CODE REVIEW

**Comment by haikuginger** [comment]
Looks good to me. @shazow, any objections? Seems reasonable to make this change before cutting 1.16/1.17.

**Comment by Lukasa** [comment]
Let's do it.

**Comment by adamchainz** [comment]
You should also update the link on the github project page

**Comment by haikuginger** [comment]
Thanks @adamchainz! If I'm not mistaken, @shazow will have to take care of that last bit. For right now, it hits a 301, so it should be fine.

**Comment by shazow** [comment]
Excellent, thank you!

**Comment by shazow** [comment]
Updated the project description too.

**Pull request merged**
