### PR TITLE
allow http/https requests through https proxy

### PR DESCRIPTION
**Pull request by phuslu**
Fix https://github.com/shazow/urllib3/issues/476

urllib3 http/https examples
```
python -c "print __import__('urllib3').ProxyManager('https://bwg.phus.lu').request('GET', 'http://httpbin.org/ip').data"
python -c "print __import__('urllib3').ProxyManager('https://bwg.phus.lu').request('GET', 'https://httpbin.org/ip').data"
```

requests http/https examples
```
python -c "print __import__('requests').get('http://httpbin.org/ip', proxies={'https': 'https://bwg.phus.lu', 'http': 'https://bwg.phus.lu'}).text"
python -c "print __import__('requests').get('https://httpbin.org/ip', proxies={'https': 'https://bwg.phus.lu', 'http': 'https://bwg.phus.lu'}).text"
```

Signed-off-by: Phus Lu <phuslu@hotmail.com>

### CODE REVIEW

**Comment by phuslu** [comment]
Thanks for your response!

> we need to write tests for this functionality before we get any where near merging it.
Yes, of course.

>  If not, presumably we just want to treat this like a plaintext proxy with the added caveat of validating a TLS cert sent by the proxy upon connection. In that case, this isn't really the right approach either.
Oh, agree you.

I will close this pull request and submit another one after I resolved this issue.

**Comment by phuslu** [comment]
Update:

python ssl module has a issue to implement `CONNECT` over https-proxy.
see http://bugs.python.org/issue29610

I will continue to working on https://github.com/phuslu/requests_httpsproxy to resolving these issues.

**Comment by phuslu** [comment]
Update:

Because of above limitation of python ssl module(same as pyOpenSSL), I figured out that only tlslite[-ng] could implement tls over tls tunnel.

Below codes show that how it works.
```
>>> import tlslite, ssl, socket
>>> sock = tlslite.TLSConnection(socket.create_connection(('127.0.0.1', 8443)))
>>> sock.handshakeClientCert()
>>> sock.sendall('CONNECT httpbin.org:443 HTTP/1.1\r\nHost: httpbin.org:443\r\n\r\n')
>>> sock.recv(1024);
'HTTP/1.1 200 OK\r\n\r\n'
>>> conn = tlslite.TLSConnection(sock)
>>> conn.handshakeClientCert()
>>> conn.sendall('GET /get HTTP/1.1\r\nHost: httpbin.org\r\n\r\n')
>>> print conn.recv(1024)
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 22 Feb 2017 14:19:51 GMT
Content-Type: application/json
Content-Length: 133
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
  "args": {}, 
  "headers": {
    "Host": "httpbin.org"
  }, 
  "origin": "153.125.235.207", 
  "url": "https://httpbin.org/get"
}
```

Will continue to `requests-httpsproxy` works base on above code snippet.

**Comment by phuslu** [comment]
Update:

A dirtry&draftly `requests_httpsproxy` prototype works in commit https://github.com/phuslu/requests_httpsproxy/tree/25e9d680cc9a6db64c461bffd06d328a49e6d86d

**Comment by phuslu** [comment]
Update:

Now `requests-httpsproxy` is available on https://github.com/phuslu/requests-httpsproxy . Thanks.

**Comment by Hunter-Zack** [comment]
@phuslu This means using HTTPS proxy with socket?

**Pull request closed without merging**
