### PR TITLE
Credit HPE for my work

### PR DESCRIPTION
**Pull request by Lukasa**

### CODE REVIEW

**Comment by shazow** [comment]
Nice, I think it's a good idea to consider employers who allow their employers to work on urllib3 in their paid time as sponsors. Maybe seeing some examples on the list will encourage more employers to do it.

Should we keep the list most-recently-active-first to promote more newcomers?

**Comment by Lukasa** [comment]
Works for me!

**Comment by sigmavirus24** [comment]
I kicked off restarts on the Travis Jobs that failed.

**Comment by haikuginger** [comment]
Grrr, looks like we've got one oddly-persistent failure across the board. Digging into it.

**Comment by haikuginger** [comment]
@Lukasa, can you rebase on master?

**Comment by haikuginger** [comment]
Ah, and can you also make your handle a link to your GitHub profile? See #1295 for an example.

**Comment by Lukasa** [comment]
ACK, done.

**Comment by haikuginger** [comment]
Thanks @Lukasa! And thanks to HPE, wherever you are!

**Pull request merged**
