### PR TITLE
Test Python 3.6 on Appveyor

### PR DESCRIPTION
**Pull request by Lukasa**
We should probably increase our test matrix to test as many versions on as many platforms as possible.

### CODE REVIEW

**Comment by Lukasa** [comment]
Well...that's a surprising test failure. I have just validated that `datetime.datetime.fromtimestamp(0)` does in fact return `OSError` on Windows under Python 3.6. I don't yet know why.

**Comment by Lukasa** [comment]
Ah, it's [Python issue 29097](https://bugs.python.org/issue29097).

**Comment by SethMichaelLarson** [comment]
You could add `3.7-dev` to Travis as well. :)

**Comment by Lukasa** [comment]
I'm a bit less interested in doing that in the CI, mostly because it's often not useful to block on bugs introduced upstream.

**Comment by sigmavirus24** [comment]
> I'm a bit less interested in doing that in the CI, mostly because it's often not useful to block on bugs introduced upstream.

You could make it an allowed failure though. That would mean people would have to check it to report issues upstream, but *shrug*

**Comment by Lukasa** [comment]
Yeah, so I've gone pretty cold on allowed-failures. *Generally speaking* it's been my experience that people don't check them, so they end up red and stay red.

**Pull request merged**
