### PR TITLE
Adding docs/requirements.txt for readthedocs.

### PR DESCRIPTION
**Pull request by jonparrott**
The rtd config will need to be updated to point to `docs/requirements.txt` instead of `docs-requirements.txt`.

I think/hope this should work.

### CODE REVIEW

**Comment by Lukasa** [comment]
This certainly *looks* about right. I'll merge, and we'll see what happens!

**Comment by Lukasa** [comment]
Argh, of course I cannot merge because master is a protected branch and this branch is out of date. Closed in favour of #913.

**Comment by Lukasa** [comment]
Hurray @jonparrott, this appears to have worked! Check out rtd for the fruits of your labour.

**Comment by jonparrott** [comment]
YAY! Thanks @Lukasa!

As I mentioned before, I'm happy to be a reviewer on docs changes and such going forward. :)

**Comment by Lukasa** [comment]
Sounds good to me!

**Pull request closed without merging**
