### PR TITLE
Let logger format messages on demand

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by Lukasa** [comment]
Seems reasonable to me. =)

**Comment by shazow** [comment]
Ah is this equivalent? Any downside? (TIL)

**Comment by scop** [comment]
I don't think there are any downsides. The most prominent upside is avoiding formatting of messages that end up being thrown away due to logging level, and the secondary is slightly cleaner code (IMO).

**Comment by shazow** [comment]
That's great, thank you. :)

**Pull request merged**
