### PR TITLE
When SSL feature warnings, aggressively direct people to upgrade

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
test failures look unrelated

**Comment by shazow** [comment]
:custard:!

**Comment by alex** [comment]
If you are interested in the science that prompted that, over the past 3 days:

- `requests` downloads are 19.1% python 2.6
- `urllib3` downloads are 12.5% python 2.6

Looking to drive those numbers down by getting people to ugprade

**Comment by shazow** [comment]
Great stuff, love wording improvements like this. Happy to try out other stuff too if you have ideas.

**Pull request merged**
