### PR TITLE
Fix dummyserver decode errors when defaults are used with Python 3

### PR DESCRIPTION
**Pull request by reversefold**
Fixes issue https://github.com/shazow/urllib3/issues/1258
I searched for any usage of request.params.get() followed by a decode on the value.

A better version of a small part of PR https://github.com/shazow/urllib3/pull/1257 with some extra fixes.

### CODE REVIEW

**Comment by Lukasa** [comment]
Hey @jonparrott do you know what's going on with the GAE builds here?

**Comment by reversefold** [comment]
@Lukasa @jonparrott After debugging the gae stuff I think I've figured out the problem. When I tested locally by installing the python env through gcloud it gave me `release: "1.9.57"` of `google_appengine`. If I download the latest the way that `_travis/install.sh` does, though, it gives me `release: "1.9.60"` which appears to have moved the `sandbox` module to `google.appengine.tools.devappserver2.python.runtime`.

I've opened a new PR for a fix: https://github.com/shazow/urllib3/pull/1265

**Comment by reversefold** [comment]
Rebased on master so the gae test should work.

**Comment by reversefold** [comment]
Rebased on master again.

**Pull request merged**
