### PR TITLE
Add trove classifiers for all supported Python versions

### PR DESCRIPTION
**Pull request by jdufresne**
I frequently use the PyPI trove classifiers to check if a 3rd party package is usable by my project. Documenting all supported versions makes this easier.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
So codecov received the information: https://codecov.io/gh/shazow/urllib3/commit/bb16fc295121aa757033708157ba3692b06a41a4 It's just not updating it's status here.

**Comment by Lukasa** [comment]
Ugh codecov what the hell?

**Comment by sigmavirus24** [comment]
Also, I can't exactly merge this manually because of our required status checks.

**Comment by Lukasa** [comment]
Yeah, we either need to fix codecov or get @shazow to put the repo in an org so someone can get permissions to remove the requirement

**Comment by jdufresne** [comment]
I did a `git commit --amend --reset-author` and pushed. codecov looks to have gone through now. I'll do the same on my other PR.

**Pull request merged**
