### PR TITLE
Append warnings.

### LINKED ISSUE #816: Honor PYTHONWARNINGS for SNIMissingWarning
.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

I'm not here to discuss the validity of those warnings, but when I tried to get rid of them with the PYTHONWARNINGS environment variable, it only works for the InsecurePlatformWarning one. The other is always displayed whatever I put in PYTHONWARNINGS.

Please advise what PYTHONWARNINGS value to use to get rid of this one, this is a documented python feature: 
https://docs.python.org/2/library/warnings.html
https://docs.python.org/2/using/cmdline.html?highlight=pythonwarnings#envvar-PYTHONWARNINGS

Also seen the same problem here: in https://github.com/shazow/urllib3/issues/497

Thanks

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/31947052-honor-pythonwarnings-for-snimissingwarning?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Lukasa**
Should resolve #816.

### CODE REVIEW

**Comment by piotr-dobrogost** [comment]
Similar fix in pip – https://github.com/pypa/pip/pull/3455

**Comment by sigmavirus24** [comment]
D'oh. Sorry @shazow forgot which project this was.

**Comment by shazow** [comment]
:+1:, @sigmavirus24 since you merged it you get to put it into CHANGES.rst :)

**Comment by sigmavirus24** [comment]
@shazow pull request for those or just push directly?

**Comment by shazow** [comment]
@sigmavirus24 Either one, feel free to push directly if it's straight-forward or PR if you'd like confirmation/feedback.

**Comment by shazow** [comment]
Btw, please #mention the issue in the CHANGES commit message. See: https://github.com/shazow/urllib3/commits/master/CHANGES.rst

**Comment by sigmavirus24** [comment]
Roger wilco

**Comment by sigmavirus24** [comment]
@shazow https://github.com/shazow/urllib3/commit/a47dbc3753f2c64e36f52c079b18c80230ce97dc

**Comment by shazow** [comment]
\<reaction=":custard:" /\>

**Comment by sigmavirus24** [comment]
@shazow if you move to GitLab you can add any reaction you want (and you would have been able to do that for *months* now).

**Comment by shazow** [comment]
I do use gitlab for some private projects, I am a fan. :) Who knows where we'll be in a year.

**Pull request merged**
