### PR TITLE
Test for set-cookies headers are lost after creating a HTTPHeaderDict using an instance of HTTPHeaderDict

### PR DESCRIPTION
**Pull request by seocam**

### CODE REVIEW

**Comment by Lukasa** [comment]
For obvious reasons, this test fails the build. That is, after all, what it's for. ;)

**Comment by sigmavirus24** [comment]
I merged this into #562

**Comment by Lukasa** [comment]
I'll leave this open until it gets merged into #563 as well.

**Comment by Lukasa** [comment]
Done. @seocam thanks for this, both current pull requests now contain your test. =) :cake:

**Pull request closed without merging**
