### PR TITLE
Add support for ChaCha20.

### PR DESCRIPTION
**Pull request by Lukasa**
ChaCha20 is coming in OpenSSL 1.1.0, and it's generally pretty excellent. OpenSSL kindly ignores requests for ciphers that it doesn't support, so we can unconditionally update our code to request ChaCha20 and expect OpenSSL to just quietly ignore the change when it doesn't know what ChaCha is.

This change has us prefer AES-GCM over ChaCha20. This decision is made mostly because newer processors have AES-NI hardware acceleration instructions, and right now we're not in a good place to query whether or not those instructions are present, so we just assume that they are. However, [CPython issue 27766](https://bugs.python.org/issue27766), in addition to making this change, also provides a private function that could be queried for AES-NI support. We may want to wait until CPython 3.6 drops to see if that function makes it in, because we could use it to be smarter about our cipher string.

### CODE REVIEW

**Comment by Lukasa** [comment]
@haikuginger Done.

**Comment by haikuginger** [comment]
Okay; I'm :+1:. @sigmavirus24?

**Comment by sigmavirus24** [comment]
@Lukasa can you add a release note for this? Otherwise I'm 👍

**Comment by Lukasa** [comment]
Release note added.

**Comment by sigmavirus24** [comment]
Thanks! I'll merge once Travis is happy

**Comment by haikuginger** [comment]
Whoops, didn't see you wanted to pull the trigger @sigmavirus24! Thanks very much @Lukasa! ✨🍻✨

**Pull request merged**
