### PR TITLE
lazily load uuid lib only where needed

### PR DESCRIPTION
**Pull request by igalic**
This should address issues such as https://github.com/requests/requests/issues/3213 in downstream libraries.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Could you add a note to our CHANGES file regarding this? Once that's there, I'm 👍

**Comment by igalic** [comment]
@sigmavirus24 unless this is a breaking change, it's now documented in CHANGES.
Is there anything I can do to address the codecoverage drop?

**Comment by igalic** [comment]
fascinating.
i added a CHANGES entry, and now everything is failing 🤣

**Comment by sigmavirus24** [comment]
@igalic, I'm not sure what you mean about the drop in coverage, I see:

```
Merging #1270 into master will not change coverage.
```

I think codecov is marked as failed because AppVeyor failed. I'll see if I can restart that build.

**Comment by sigmavirus24** [comment]
And I can't. I don't know who can. :disappointed:

**Comment by SethMichaelLarson** [comment]
Does AppVeyor react to a close->open like Travis does?

**Comment by igalic** [comment]
i did a `push --force` perhaps that confused AppVeyor & codecov?

**Comment by SethMichaelLarson** [comment]
:tada: Glad the close-open trick worked. :)

**Comment by igalic** [comment]
n.b.: This optimization might be obsoleted thru https://github.com/python/cpython/pull/3684

**Pull request merged**
