### PR TITLE
fix connectionpool.ConnectionPool.close()

### PR DESCRIPTION
**Pull request by tharvik**
See #873 for reference.

### CODE REVIEW

**Comment by Lukasa** [comment]
Hrrrm, those test failures *seem* to be unrelated to this change: something is going on with install. I'll investigate.

**Comment by Lukasa** [comment]
Cool, we bumped into [this](https://bugs.launchpad.net/pkginfo/+bug/1585006). No point piling on, the reports are already there, so let's just work around.

**Comment by Lukasa** [comment]
Fab, so I've proposed a fix that should resolve the busted tests in #875. When that (or something like it) gets merged, you'll need to rebase on top of it to solve the test failures.

Sorry about that inconvenience!

**Comment by haikuginger** [comment]
While we're in here, should we switch from `pass` to a `NotImplemented` exception akin to `RequestMethods.urlopen()`?

**Comment by tharvik** [comment]
> While we're in here, should we switch from pass to a NotImplemented exception akin to RequestMethods.urlopen()?

That would be even nicer, I'll do it when #875 is merged.

**Comment by Lukasa** [comment]
@haikuginger @tharvik I don't actually think we want to do that. I think we shouldn't punish people who unconditionally call `super()` in `close()`, and it gives us the opportunity to be a bit more flexible later.

**Comment by haikuginger** [comment]
I'll defer to @Lukasa's judgement on that, then; I'm 👍 on this change.

**Comment by tharvik** [comment]
Okay, I won't add anything to the PR then.

**Comment by Lukasa** [comment]
All better, mergy mergy mergy. Thanks @tharvik! :sparkles:

**Comment by sigmavirus24** [comment]
@Lukasa you did the merge, don't forget the release notes ;)

**Comment by haikuginger** [comment]
Thanks very much @tharvik! 🍰

**Pull request merged**
