### PR TITLE
Make sure we distribute backports.

### LINKED ISSUE #839: PyOpenSSL: Fails to import after installation with the provided instructions
The [Security documentation page] indicates that to use PyOpenSSL that you must first install:

* pip3 install pyopenssl ndg-httpsclient pyasn1

And then in a Python interpreter run:

* import urllib3.contrib.pyopenssl
* urllib3.contrib.pyopenssl.inject_into_urllib3()

However on Python 3.4.4 (the latest 3.4.x) on OS X 10.11 (the latest OS X) I get the following traceback when executing `import urllib3.contrib.pyopenssl`:

```
Traceback (most recent call last):
  File "/Users/davidf/Projects/webcrystal/venv/lib/python3.4/site-packages/urllib3/contrib/pyopenssl.py", line 60, in <module>
    from socket import _fileobject
ImportError: cannot import name '_fileobject'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/davidf/Projects/webcrystal/venv/lib/python3.4/site-packages/urllib3/contrib/pyopenssl.py", line 63, in <module>
    from urllib3.packages.backports.makefile import backport_makefile
ImportError: No module named 'urllib3.packages.backports'
```

Perhaps there is some missing step in the documentation?

[Security documentation page]: https://urllib3.readthedocs.org/en/latest/security.html#openssl-pyopenssl

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/32808776-pyopenssl-fails-to-import-after-installation-with-the-provided-instructions?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Lukasa**
Resolves #839.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
:tada:

**Comment by shazow** [comment]
Good call, I need to push out v1.15.1 for this, right?

**Comment by Lukasa** [comment]
@shazow Yes. =)

**Comment by shazow** [comment]
Done.

**Pull request merged**
