### PR TITLE
Cast OpenSSL errors to strings.

### LINKED ISSUE #556: Need to update error handling for pyOpenSSL
If an `SSLError` comes from `pyOpenSSL`, we attempt to determine if it's an error due to request timeouts on python 2.6 being raised as `BaseSSLErrors` [here](https://github.com/shazow/urllib3/blob/29aa09bde9c42cc9a8d79aac47ee3d362b438cca/urllib3/connectionpool.py#L314). If the handshake ends unexpectedly under pyOpenSSL, then we get an `SSLError` that has a captured `SysCallError` which when you call `str(SSLError(msg, SysCallError(code, msg)))` you get

```py
TypeError: __str__ returned non-string (type SysCallError)
```

So we might want to update how we handle SSLErrors to accomodate pyOpenSSL. To be clear, I observed this on: python 2.7.9 with openssl 1.0.1l (from brew) and I was using requests to debug an issue with `https://apissl.cloudfactory.com`, e.g., `requests.get('https://apissl.cloudfactory.com')`

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9051543-need-to-update-error-handling-for-pyopenssl?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Lukasa**
Resolves #556.

I haven't written any tests for this because of #791. I'll start trying to work on #791 and, if we can get it ironed out quickly, we should block the merge of this behind #791 so that we can actually have a test for this.

### CODE REVIEW

**Comment by borbamartin** [comment]
+1
Worked for me. Thanks @Lukasa

**Comment by shazow** [comment]
:custard:

**Comment by qicongchen** [comment]
I have changed this line but still have this error.

**Comment by Lukasa** [comment]
@qicongchen What error, specifically?

**Comment by Phoenix-Chen** [comment]
Same here. I changed the line by adding `str()` around e. But the Error is still there.
`File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 318, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)`

I also tried deleting the whole check condition:
`        if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
            raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)`

Then I got the following error:
`  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError`

Help please!!!

**Comment by sigmavirus24** [comment]
@Phoenix-Chen can you provide more details?

It's clear you're using requests.

- What version of requests are you using?
- What file did you edit to add the `str()`?
- How did you install requests?
- What version of Python are you using? (`python -V`)

**Comment by jbrockmendel** [comment]
I got this error on 2017-01-21.  The logs I'm looking at are spotty, but here is what I have:

2017-01-21 12:29:26.216
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 351, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 814, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 350, in ssl_wrap_socket
    rd, _, _ = select.select([sock], [], [], sock.gettimeout())
error: (4, 'Interrupted system call')
```

2017-01-21 12:34:15.539
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 71, in get
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 403, in send
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 354, in _make_request
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 324, in _raise_timeout
TypeError: __str__ returned non-string (type Error)
```

I am assuming the two errors are related based on the timing.

The line numbers don't line up with the requests/urllib3 versions currently installed, so I don't know the exact release versions that were running at the time.  Looks like somewhere around here: https://github.com/shazow/urllib3/blob/7fa026c37a5326dcaf97cb9c66ecd15df9c1a194/urllib3/connectionpool.py

Ubuntu 16.04, Python 2.7.12

**Comment by Lukasa** [comment]
Hrm. =(

So the first one is an issue that got fixed recently, which is that we didn't handle EINTR while doing select operations on a socket.

The second one is still the one we need more details on. If you're seeing regular reproduction of this issue, it'd be nice to add a try...except around the cast to string and to print out the exception itself, ideally with a traceback.

**Comment by SethMichaelLarson** [comment]
Huzzah for pretending to always implement PEP 475. :)

**Comment by jbrockmendel** [comment]
@Lukasa I'd prefer not to tinker the code directly in dist-packages.  Will a patch at import-time (or instantiation) get the job done?  Something like:

```
def patch_raise_timeout(pool):
	_orig_raise_timeout = pool._raise_timeout

	def _raise_timeout(err, url, timeout_value):
		try:
			strerror = str(err)
		except TypeError:
			raise err
		else:
			_orig_raise_timeout(err, url, timeout_value)


	pool._raise_timeout = _raise_timeout
```

This error has come up before, but not regularly.  I'll post next time it shows up in the logs.

**Comment by Lukasa** [comment]
That might work.

**Pull request merged**
