### PR TITLE
Spelling fixes

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by Lukasa** [comment]
Hrm, those failures are not really relevant: it seems that flake8 is catching some new errors.

**Comment by haikuginger** [comment]
Doesn't look like it's catching new errors; it just seems to be ignoring our `# noqa` flags on those lines.

**Comment by sigmavirus24** [comment]
That should be fixed tonight ;)

**Comment by haikuginger** [comment]
> That should be fixed tonight ;)

Such foresight! ;)

**Comment by Lukasa** [comment]
Please rebase on the new master. =)

**Comment by haikuginger** [comment]
Well, I like spelling fixes! 👍

**Comment by sigmavirus24** [comment]
Thanks again @scop!

**Pull request merged**
