### PR TITLE
Fixing appengine tests

### LINKED ISSUE #697: AppEngine tests failing on travis
```
Traceback (most recent call last):
  File ".tox/gae/bin/nosetests", line 11, in <module>
    sys.exit(run_exit())
  File "/home/travis/build/shazow/urllib3/.tox/gae/lib/python2.7/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/opt/python/2.7.9/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/home/travis/build/shazow/urllib3/.tox/gae/lib/python2.7/site-packages/nose/core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/home/travis/build/shazow/urllib3/.tox/gae/lib/python2.7/site-packages/nose/config.py", line 346, in configure
    self.plugins.configure(options, self)
  File "/home/travis/build/shazow/urllib3/.tox/gae/lib/python2.7/site-packages/nose/plugins/manager.py", line 284, in configure
    cfg(options, config)
  File "/home/travis/build/shazow/urllib3/.tox/gae/lib/python2.7/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/travis/build/shazow/urllib3/.tox/gae/lib/python2.7/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/travis/build/shazow/urllib3/.tox/gae/lib/python2.7/site-packages/nosegae.py", line 91, in configure
    import dev_appserver
ImportError: No module named dev_appserver
ERROR: InvocationError: '/home/travis/build/shazow/urllib3/.tox/gae/bin/nosetests -c /home/travis/build/shazow/urllib3/test/appengine/nose.cfg test/appengine'
```

https://travis-ci.org/shazow/urllib3/jobs/76562407

@jonparrott Could you take a look please?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26023268-appengine-tests-failing-on-travis?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jonparrott**
Pulling code from Google/oauth2client to fetch the newest SDK.

Fingers crossed that this will work the first time. Travis can be belligerent about caching.

Fixes #697.

### CODE REVIEW

**Comment by jonparrott** [comment]
Alright, it only took me 4 tries, but travis is now green! Ready to review/merge.

**Comment by Lukasa** [comment]
If it were me I'd rather use a `_travis/` directory than a `scripts/` one, but otherwise this seems fine.

**Comment by shazow** [comment]
@jonparrott Thank you!

+1 on moving it into `_travis/` (or even `.travis/`).

**Comment by jonparrott** [comment]
I'll switch it over to ``_travis`` a little later on this evening - I have to go to a hackathon. ;)

**Comment by shazow** [comment]
@jonparrott Sweet, hack up a storm!

**Comment by jonparrott** [comment]
Alright, should be good to go.

**Comment by shazow** [comment]
Thank you! :custard:

**Pull request merged**
