### PR TITLE
Stop relying on the stdlib's default cipher list

### PR DESCRIPTION
**Pull request by sigmavirus24**
urllib3's release cadence is much faster so it's preferable if
urllib3 handles its own default cipher list as it will undoubtedly
be more quickly updated/released.

### CODE REVIEW

**Comment by shazow** [comment]
+1 to @kevinburke, otherwise looks good.

**Comment by dstufft** [comment]
I would actually personally drop the ``HIGH`` ciphers, almost nothing is going to require them and the only reason the stdlib has them is because it was the only way I could get them to agree to a stricter cipher list.

**Comment by t-8ch** [comment]
@sigmavirus24 We have another cipherlist declaration in contrib/pyopenssl. Can you change this, so both use the same?

**Comment by Lukasa** [comment]
Superseded by #588.

**Pull request closed without merging**
